apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deploy
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: front-end
      region: asia
  template:
    metadata:
      app: front-end
      region: asia
    spec:
      containers:
        - image: nginx:latest
          name: nginx-container
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          restartPolicy: OnFailure
---
apiVersion: v1
kind: Service
metadata:  
  name: nginx-svc
spec:
  type: NodePort
  selector:
    app: front-end
    region: asia
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 3333
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: netpol
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: default
          podSelector:
            matchLabels:
              app: my-app
    - from:
        ipBlock:
          cidr: 101.0.63.221/32
          
