apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deploy
  namespace: test
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: front-end
      region: asia
  template:
    metadata:
      labels:
        app: front-end
        region: asia
    spec:
      containers:
        - image: nginx:latest
          name: nginx-container
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          restartPolicy: OnFailure
---
apiVersion: v1
kind: Service
metadata:  
  name: nginx-svc
  namespace: test
spec:
  type: NodePort
  selector:
    app: front-end
    region: asia
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 32022
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: netpol
  namespace: test
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: default
          podSelector:
            matchLabels:
              app: my-app
    - from:
        - ipBlock:
            cidr: 192.168.1.39/32
        - ipBlock:
            cidr: 101.0.63.221/32
      ports:
        - port: 80
          protocol: TCP
          
